// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/agumiroff/BigTechProject/inventory/v1/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InvService is an autogenerated mock type for the InvService type
type InvService struct {
	mock.Mock
}

type InvService_Expecter struct {
	mock *mock.Mock
}

func (_m *InvService) EXPECT() *InvService_Expecter {
	return &InvService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, uuid
func (_m *InvService) GetPart(ctx context.Context, uuid string) (*model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InvService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InvService_Expecter) GetPart(ctx interface{}, uuid interface{}) *InvService_GetPart_Call {
	return &InvService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *InvService_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *InvService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InvService_GetPart_Call) Return(res *model.Part, err error) *InvService_GetPart_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *InvService_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *InvService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, f
func (_m *InvService) ListParts(ctx context.Context, f *model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PartsFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InvService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - f *model.PartsFilter
func (_e *InvService_Expecter) ListParts(ctx interface{}, f interface{}) *InvService_ListParts_Call {
	return &InvService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, f)}
}

func (_c *InvService_ListParts_Call) Run(run func(ctx context.Context, f *model.PartsFilter)) *InvService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *InvService_ListParts_Call) Return(res []*model.Part, err error) *InvService_ListParts_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *InvService_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) ([]*model.Part, error)) *InvService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvService creates a new instance of InvService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvService {
	mock := &InvService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
