// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	order_v1 "github.com/agumiroff/BigTechProject/shared/pkg/openapi/v1"
)

// OrderHandler is an autogenerated mock type for the OrderHandler type
type OrderHandler struct {
	mock.Mock
}

type OrderHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderHandler) EXPECT() *OrderHandler_Expecter {
	return &OrderHandler_Expecter{mock: &_m.Mock}
}

// CancelOrderByUuid provides a mock function with given fields: ctx, params
func (_m *OrderHandler) CancelOrderByUuid(ctx context.Context, params order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUuid")
	}

	var r0 order_v1.CancelOrderByUuidRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.CancelOrderByUuidParams) order_v1.CancelOrderByUuidRes); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.CancelOrderByUuidRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, order_v1.CancelOrderByUuidParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHandler_CancelOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUuid'
type OrderHandler_CancelOrderByUuid_Call struct {
	*mock.Call
}

// CancelOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - params order_v1.CancelOrderByUuidParams
func (_e *OrderHandler_Expecter) CancelOrderByUuid(ctx interface{}, params interface{}) *OrderHandler_CancelOrderByUuid_Call {
	return &OrderHandler_CancelOrderByUuid_Call{Call: _e.mock.On("CancelOrderByUuid", ctx, params)}
}

func (_c *OrderHandler_CancelOrderByUuid_Call) Run(run func(ctx context.Context, params order_v1.CancelOrderByUuidParams)) *OrderHandler_CancelOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(order_v1.CancelOrderByUuidParams))
	})
	return _c
}

func (_c *OrderHandler_CancelOrderByUuid_Call) Return(_a0 order_v1.CancelOrderByUuidRes, _a1 error) *OrderHandler_CancelOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderHandler_CancelOrderByUuid_Call) RunAndReturn(run func(context.Context, order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error)) *OrderHandler_CancelOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderHandler) CreateOrder(ctx context.Context, req *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 order_v1.CreateOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) order_v1.CreateOrderRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.CreateOrderRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHandler_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderHandler_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *order_v1.CreateOrderRequest
func (_e *OrderHandler_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderHandler_CreateOrder_Call {
	return &OrderHandler_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderHandler_CreateOrder_Call) Run(run func(ctx context.Context, req *order_v1.CreateOrderRequest)) *OrderHandler_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_v1.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderHandler_CreateOrder_Call) Return(_a0 order_v1.CreateOrderRes, _a1 error) *OrderHandler_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderHandler_CreateOrder_Call) RunAndReturn(run func(context.Context, *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error)) *OrderHandler_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUuid provides a mock function with given fields: ctx, params
func (_m *OrderHandler) GetOrderByUuid(ctx context.Context, params order_v1.GetOrderByUuidParams) (order_v1.Order, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUuid")
	}

	var r0 order_v1.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.GetOrderByUuidParams) (order_v1.Order, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.GetOrderByUuidParams) order_v1.Order); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(order_v1.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, order_v1.GetOrderByUuidParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHandler_GetOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUuid'
type OrderHandler_GetOrderByUuid_Call struct {
	*mock.Call
}

// GetOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - params order_v1.GetOrderByUuidParams
func (_e *OrderHandler_Expecter) GetOrderByUuid(ctx interface{}, params interface{}) *OrderHandler_GetOrderByUuid_Call {
	return &OrderHandler_GetOrderByUuid_Call{Call: _e.mock.On("GetOrderByUuid", ctx, params)}
}

func (_c *OrderHandler_GetOrderByUuid_Call) Run(run func(ctx context.Context, params order_v1.GetOrderByUuidParams)) *OrderHandler_GetOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(order_v1.GetOrderByUuidParams))
	})
	return _c
}

func (_c *OrderHandler_GetOrderByUuid_Call) Return(_a0 order_v1.Order, _a1 error) *OrderHandler_GetOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderHandler_GetOrderByUuid_Call) RunAndReturn(run func(context.Context, order_v1.GetOrderByUuidParams) (order_v1.Order, error)) *OrderHandler_GetOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// NewError provides a mock function with given fields: ctx, err
func (_m *OrderHandler) NewError(ctx context.Context, err error) *order_v1.GenericErrorStatusCode {
	ret := _m.Called(ctx, err)

	if len(ret) == 0 {
		panic("no return value specified for NewError")
	}

	var r0 *order_v1.GenericErrorStatusCode
	if rf, ok := ret.Get(0).(func(context.Context, error) *order_v1.GenericErrorStatusCode); ok {
		r0 = rf(ctx, err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.GenericErrorStatusCode)
		}
	}

	return r0
}

// OrderHandler_NewError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewError'
type OrderHandler_NewError_Call struct {
	*mock.Call
}

// NewError is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *OrderHandler_Expecter) NewError(ctx interface{}, err interface{}) *OrderHandler_NewError_Call {
	return &OrderHandler_NewError_Call{Call: _e.mock.On("NewError", ctx, err)}
}

func (_c *OrderHandler_NewError_Call) Run(run func(ctx context.Context, err error)) *OrderHandler_NewError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(error))
	})
	return _c
}

func (_c *OrderHandler_NewError_Call) Return(_a0 *order_v1.GenericErrorStatusCode) *OrderHandler_NewError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHandler_NewError_Call) RunAndReturn(run func(context.Context, error) *order_v1.GenericErrorStatusCode) *OrderHandler_NewError_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, req, params
func (_m *OrderHandler) PayOrder(ctx context.Context, req *order_v1.PayOrderRequest, params order_v1.PayOrderParams) (order_v1.PayOrderRes, error) {
	ret := _m.Called(ctx, req, params)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 order_v1.PayOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) (order_v1.PayOrderRes, error)); ok {
		return rf(ctx, req, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) order_v1.PayOrderRes); ok {
		r0 = rf(ctx, req, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.PayOrderRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) error); ok {
		r1 = rf(ctx, req, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHandler_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderHandler_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *order_v1.PayOrderRequest
//   - params order_v1.PayOrderParams
func (_e *OrderHandler_Expecter) PayOrder(ctx interface{}, req interface{}, params interface{}) *OrderHandler_PayOrder_Call {
	return &OrderHandler_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, req, params)}
}

func (_c *OrderHandler_PayOrder_Call) Run(run func(ctx context.Context, req *order_v1.PayOrderRequest, params order_v1.PayOrderParams)) *OrderHandler_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_v1.PayOrderRequest), args[2].(order_v1.PayOrderParams))
	})
	return _c
}

func (_c *OrderHandler_PayOrder_Call) Return(_a0 order_v1.PayOrderRes, _a1 error) *OrderHandler_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderHandler_PayOrder_Call) RunAndReturn(run func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) (order_v1.PayOrderRes, error)) *OrderHandler_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderHandler creates a new instance of OrderHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHandler {
	mock := &OrderHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
