// Code generated by ogen, DO NOT EDIT.

package orders_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetOrderByIDOperation    OperationName = "GetOrderByID"
	UpdateOrderByIDOperation OperationName = "UpdateOrderByID"
)
