// Code generated by ogen, DO NOT EDIT.

package orders_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOrderByID implements GetOrderByID operation.
//
// Get order data for order ID.
//
// GET /api/orders/v1/{order_id}
func (UnimplementedHandler) GetOrderByID(ctx context.Context, params GetOrderByIDParams) (r GetOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrderByID implements UpdateOrderByID operation.
//
// Update order data for order ID.
//
// PUT /api/orders/v1/{order_id}
func (UnimplementedHandler) UpdateOrderByID(ctx context.Context, req *Order, params UpdateOrderByIDParams) (r UpdateOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}
