// Code generated by ogen, DO NOT EDIT.

package orders_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetOrderByID implements GetOrderByID operation.
	//
	// Get order data for order ID.
	//
	// GET /api/orders/v1/{order_id}
	GetOrderByID(ctx context.Context, params GetOrderByIDParams) (GetOrderByIDRes, error)
	// UpdateOrderByID implements UpdateOrderByID operation.
	//
	// Update order data for order ID.
	//
	// PUT /api/orders/v1/{order_id}
	UpdateOrderByID(ctx context.Context, req *Order, params UpdateOrderByIDParams) (UpdateOrderByIDRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
