// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	order_v1 "github.com/agumiroff/BigTechProject/shared/pkg/openapi/v1"
	mock "github.com/stretchr/testify/mock"
)

// OrderAPI is an autogenerated mock type for the OrderAPI type
type OrderAPI struct {
	mock.Mock
}

type OrderAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderAPI) EXPECT() *OrderAPI_Expecter {
	return &OrderAPI_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, params
func (_m *OrderAPI) CancelOrder(ctx context.Context, params order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 order_v1.CancelOrderByUuidRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.CancelOrderByUuidParams) order_v1.CancelOrderByUuidRes); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.CancelOrderByUuidRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, order_v1.CancelOrderByUuidParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderAPI_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderAPI_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - params order_v1.CancelOrderByUuidParams
func (_e *OrderAPI_Expecter) CancelOrder(ctx interface{}, params interface{}) *OrderAPI_CancelOrder_Call {
	return &OrderAPI_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, params)}
}

func (_c *OrderAPI_CancelOrder_Call) Run(run func(ctx context.Context, params order_v1.CancelOrderByUuidParams)) *OrderAPI_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(order_v1.CancelOrderByUuidParams))
	})
	return _c
}

func (_c *OrderAPI_CancelOrder_Call) Return(_a0 order_v1.CancelOrderByUuidRes, _a1 error) *OrderAPI_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderAPI_CancelOrder_Call) RunAndReturn(run func(context.Context, order_v1.CancelOrderByUuidParams) (order_v1.CancelOrderByUuidRes, error)) *OrderAPI_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderAPI) CreateOrder(ctx context.Context, req *order_v1.CreateOrderRequest) (*order_v1.CreateOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *order_v1.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) (*order_v1.CreateOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) *order_v1.CreateOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderAPI_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderAPI_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *order_v1.CreateOrderRequest
func (_e *OrderAPI_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderAPI_CreateOrder_Call {
	return &OrderAPI_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderAPI_CreateOrder_Call) Run(run func(ctx context.Context, req *order_v1.CreateOrderRequest)) *OrderAPI_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_v1.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderAPI_CreateOrder_Call) Return(res *order_v1.CreateOrderResponse, err error) *OrderAPI_CreateOrder_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *OrderAPI_CreateOrder_Call) RunAndReturn(run func(context.Context, *order_v1.CreateOrderRequest) (*order_v1.CreateOrderResponse, error)) *OrderAPI_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, req
func (_m *OrderAPI) GetOrder(ctx context.Context, req order_v1.GetOrderByUuidParams) (*order_v1.Order, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *order_v1.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.GetOrderByUuidParams) (*order_v1.Order, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, order_v1.GetOrderByUuidParams) *order_v1.Order); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, order_v1.GetOrderByUuidParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderAPI_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderAPI_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req order_v1.GetOrderByUuidParams
func (_e *OrderAPI_Expecter) GetOrder(ctx interface{}, req interface{}) *OrderAPI_GetOrder_Call {
	return &OrderAPI_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, req)}
}

func (_c *OrderAPI_GetOrder_Call) Run(run func(ctx context.Context, req order_v1.GetOrderByUuidParams)) *OrderAPI_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(order_v1.GetOrderByUuidParams))
	})
	return _c
}

func (_c *OrderAPI_GetOrder_Call) Return(res *order_v1.Order, err error) *OrderAPI_GetOrder_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *OrderAPI_GetOrder_Call) RunAndReturn(run func(context.Context, order_v1.GetOrderByUuidParams) (*order_v1.Order, error)) *OrderAPI_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, req, params
func (_m *OrderAPI) PayOrder(ctx context.Context, req *order_v1.PayOrderRequest, params order_v1.PayOrderParams) (*order_v1.PayOrderResponse, error) {
	ret := _m.Called(ctx, req, params)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *order_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) (*order_v1.PayOrderResponse, error)); ok {
		return rf(ctx, req, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) *order_v1.PayOrderResponse); ok {
		r0 = rf(ctx, req, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) error); ok {
		r1 = rf(ctx, req, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderAPI_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderAPI_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *order_v1.PayOrderRequest
//   - params order_v1.PayOrderParams
func (_e *OrderAPI_Expecter) PayOrder(ctx interface{}, req interface{}, params interface{}) *OrderAPI_PayOrder_Call {
	return &OrderAPI_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, req, params)}
}

func (_c *OrderAPI_PayOrder_Call) Run(run func(ctx context.Context, req *order_v1.PayOrderRequest, params order_v1.PayOrderParams)) *OrderAPI_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_v1.PayOrderRequest), args[2].(order_v1.PayOrderParams))
	})
	return _c
}

func (_c *OrderAPI_PayOrder_Call) Return(_a0 *order_v1.PayOrderResponse, _a1 error) *OrderAPI_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderAPI_PayOrder_Call) RunAndReturn(run func(context.Context, *order_v1.PayOrderRequest, order_v1.PayOrderParams) (*order_v1.PayOrderResponse, error)) *OrderAPI_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderAPI creates a new instance of OrderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderAPI {
	mock := &OrderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
