// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/agumiroff/BigTechProject/order/v1/internal/model"
	mock "github.com/stretchr/testify/mock"

	repositorymodel "github.com/agumiroff/BigTechProject/order/v1/internal/repository/model"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: req
func (_m *OrderRepository) CreateOrder(req *model.Order) *model.CreateOrderResponse {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.CreateOrderResponse
	if rf, ok := ret.Get(0).(func(*model.Order) *model.CreateOrderResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateOrderResponse)
		}
	}

	return r0
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - req *model.Order
func (_e *OrderRepository_Expecter) CreateOrder(req interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", req)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(req *model.Order)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(res *model.CreateOrderResponse) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(res)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(*model.Order) *model.CreateOrderResponse) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: uuid
func (_m *OrderRepository) DeleteOrder(uuid string) error {
	ret := _m.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type OrderRepository_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - uuid string
func (_e *OrderRepository_Expecter) DeleteOrder(uuid interface{}) *OrderRepository_DeleteOrder_Call {
	return &OrderRepository_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", uuid)}
}

func (_c *OrderRepository_DeleteOrder_Call) Run(run func(uuid string)) *OrderRepository_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_DeleteOrder_Call) Return(_a0 error) *OrderRepository_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_DeleteOrder_Call) RunAndReturn(run func(string) error) *OrderRepository_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: uuid
func (_m *OrderRepository) Get(uuid string) (*repositorymodel.Order, error) {
	ret := _m.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repositorymodel.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repositorymodel.Order, error)); ok {
		return rf(uuid)
	}
	if rf, ok := ret.Get(0).(func(string) *repositorymodel.Order); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositorymodel.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uuid string
func (_e *OrderRepository_Expecter) Get(uuid interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", uuid)}
}

func (_c *OrderRepository_Get_Call) Run(run func(uuid string)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(_a0 *repositorymodel.Order, _a1 error) *OrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(string) (*repositorymodel.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, m
func (_m *OrderRepository) UpdateOrder(ctx context.Context, m *model.Order) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - m *model.Order
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, m interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, m)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, m *model.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, *model.Order) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
