// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/agumiroff/BigTechProject/order/v1/internal/repository/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) CancelOrder(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderRepository_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) CancelOrder(ctx interface{}, uuid interface{}) *OrderRepository_CancelOrder_Call {
	return &OrderRepository_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, uuid)}
}

func (_c *OrderRepository_CancelOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) Return(_a0 error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order, parts
func (_m *OrderRepository) CreateOrder(ctx context.Context, order *model.OrderRow, parts []string) (string, error) {
	ret := _m.Called(ctx, order, parts)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRow, []string) (string, error)); ok {
		return rf(ctx, order, parts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRow, []string) string); ok {
		r0 = rf(ctx, order, parts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OrderRow, []string) error); ok {
		r1 = rf(ctx, order, parts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.OrderRow
//   - parts []string
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}, parts interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order, parts)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order *model.OrderRow, parts []string)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrderRow), args[2].([]string))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 string, _a1 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.OrderRow, []string) (string, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) DeleteOrder(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type OrderRepository_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) DeleteOrder(ctx interface{}, uuid interface{}) *OrderRepository_DeleteOrder_Call {
	return &OrderRepository_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, uuid)}
}

func (_c *OrderRepository_DeleteOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_DeleteOrder_Call) Return(_a0 error) *OrderRepository_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_DeleteOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderRepository_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) GetOrder(ctx context.Context, uuid string) (*model.OrderRow, []string, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.OrderRow
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrderRow, []string, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrderRow); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []string); ok {
		r1 = rf(ctx, uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, uuid)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrder(ctx interface{}, uuid interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(order *model.OrderRow, parts []string, err error) *OrderRepository_GetOrder_Call {
	_c.Call.Return(order, parts, err)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*model.OrderRow, []string, error)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) UpdateOrder(ctx context.Context, order *model.OrderRow) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRow) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.OrderRow
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, order *model.OrderRow)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrderRow))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, *model.OrderRow) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
