// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/agumiroff/BigTechProject/order/v1/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderService) CancelOrder(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, uuid interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, uuid)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 error) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) CreateOrder(ctx context.Context, req *model.CreateOrderRequest) (*model.CreateOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) (*model.CreateOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) *model.CreateOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, req *model.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(res *model.CreateOrderResponse, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.CreateOrderRequest) (*model.CreateOrderResponse, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderService) DeleteOrder(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type OrderService_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderService_Expecter) DeleteOrder(ctx interface{}, uuid interface{}) *OrderService_DeleteOrder_Call {
	return &OrderService_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, uuid)}
}

func (_c *OrderService_DeleteOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderService_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_DeleteOrder_Call) Return(_a0 error) *OrderService_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_DeleteOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, uuid
func (_m *OrderService) GetOrder(ctx context.Context, uuid string) (*model.Order, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, uuid interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) PayOrder(ctx context.Context, req *model.PayOrderRequest) (*model.PayOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *model.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest) (*model.PayOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest) *model.PayOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PayOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.PayOrderRequest
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, req interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, req)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, req *model.PayOrderRequest)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PayOrderRequest))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(res *model.PayOrderResponse, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(context.Context, *model.PayOrderRequest) (*model.PayOrderResponse, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
